
FROM ubuntu:20.04

ENV DEBIAN_FRONTEND=noninteractive

# Common package setup
RUN set -xe; \
    # Install pacakges to allow us to install other packages
    apt-get -y update; \
    apt-get -y install --no-install-recommends \
        apt-transport-https ca-certificates gnupg software-properties-common wget; \
    # Add kiware repository for CMake
    wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | apt-key add -; \
    apt-add-repository -y -n 'https://apt.kitware.com/ubuntu/'; \
    apt-add-repository -y -n 'ppa:ubuntu-toolchain-r/test'; \
    apt-get -y update; \
    # Install generic build tools & python
    apt-get -y install --no-install-recommends \
        cmake pkg-config make \
        python3 python3-pip python3-setuptools \
        ; \
    # Cleanup apt packages
    rm -rf /var/lib/apt/lists/*; \
    # Install conan
    python3 -m pip install conan
