{% extends "Dockerfile.base.j2" %}

{% block compiler_setup %}
RUN set -xe; \
    apt-get -y update; \
    apt-get -y install --no-install-recommends \
        # Install GCC
        g++-{{ gcc_version }} \
    ; \
    rm -rf /var/lib/apt/lists/*; \
    update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-{{ gcc_version }} 100 \
        --slave /usr/bin/g++ g++ /usr/bin/g++-{{ gcc_version }}
{% endblock compiler_setup %}
