
FROM {{ base_image }}

ENV DEBIAN_FRONTEND=noninteractive

RUN set -xe; \
    # Add repository to get clang from
    wget -qO - https://apt.llvm.org/llvm-snapshot.gpg.key | apt-key add -; \
    apt-add-repository -y -n "deb http://apt.llvm.org/$(lsb_release -cs)/ llvm-toolchain-$(lsb_release -cs)-{{ clang_repo_version }} main"; \

    apt-get -y update; \
    apt-get -y install --no-install-recommends \
        # Install clang & tools
        clang++-{{ clang_version }} libc++-{{ clang_version }}-dev libc++abi-{{ clang_version }}-dev \
        clang-tidy-{{ clang_version }} clang-format-{{ clang_version }} \
    ; \
    rm -rf /var/lib/apt/lists/*; \
    update-alternatives --install /usr/bin/clang clang /usr/bin/clang-{{ clang_version }} 100  \
        --slave /usr/bin/clang-format clang-format /usr/bin/clang-format-{{ clang_version }} \
        --slave /usr/bin/clang-tidy clang-tidy /usr/bin/clang-tidy-{{ clang_version }} \
        --slave /usr/bin/gcc gcc /usr/bin/clang-{{ clang_version }} \
        --slave /usr/bin/g++ g++ /usr/bin/clang-{{ clang_version }}

# Copy version information
COPY cur_version /usr/local/etc/action-cxx-toolkit/version
COPY cur_version_date /usr/local/etc/action-cxx-toolkit/version_date

# The entry point
COPY entrypoint.py /usr/local/bin/entrypoint.py
ENTRYPOINT ["/usr/local/bin/entrypoint.py"]
